### ISSUE TITLE
unicode里面正则那应该是test

### ISSUE THREAD

**Issue by zemor923** [pushmetop/30-seconds-for-everyday#2]
字符编码那篇文章正则匹配那测试应该是test，写成了text

**Comment by zhangxiangliang** [comment]
已修正，谢谢你！
下次可以直接提 `pull request` 我直接把你合并进来。

[fix: 修正《字符编码排雷录》中的拼写错误（感谢zhangzhimiao同学）](https://github.com/pushmetop/30-seconds-for-everyday/commit/be1253186d94a31a120b10c9a60ff89e270a7f3b)
